# Generated by Selenium IDE
import pytest
import time
from selenium import webdriver
from selenium.webdriver.common.by import By

class TestPruebaParcial:
  def setup_method(self, method):
    self.driver = webdriver.Chrome()  # Usar Firefox como navegador
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()  # Cerrar el navegador al finalizar

  def test_prueba_parcial(self):
    # Abrir un archivo para guardar los resultados
    with open("resultados_selenium.log", "w") as log_file:
      for i in range(100):  # Ejecutar la prueba 100 veces
        try:
          # Abrir la página de login
          self.driver.get("http://localhost/parcial_max/index.php")
          self.driver.set_window_size(801, 692)

          # Ingresar credenciales
          self.driver.find_element(By.NAME, "email").send_keys("maxito123@hotmail.com")
          self.driver.find_element(By.NAME, "password").send_keys("123456")
          self.driver.find_element(By.NAME, "login").click()

          # Esperar un momento para que la página cargue
          time.sleep(2)

          # Verificar si el login fue exitoso
          if "Bienvenido" in self.driver.page_source:
            log_file.write(f"Prueba {i + 1}: Login exitoso\n")
          else:
            log_file.write(f"Prueba {i + 1}: Fallo en el login\n")

        except Exception as e:
          # Registrar errores en el archivo de log
          log_file.write(f"Prueba {i + 1}: Error - {str(e)}\n")

        # Esperar 1 segundo entre pruebas para no sobrecargar el servidor
        time.sleep(1)


# Ejecutar la prueba
if __name__ == "__main__":
  pytest.main()